[[language]]
name="html"
formatter={command='C:\Users\studio-pc\AppData\Roaming\npm\prettier.cmd',args=["--parser","html"]}

[[language]]
name="json"
formatter={command='C:\Users\studio-pc\AppData\Roaming\npm\prettier.cmd',args=["--parser","json"]}

[[language]]
name="css"
formatter={command='C:\Users\studio-pc\AppData\Roaming\npm\prettier.cmd',args=["--parser","css"]}

[[language]]
name="javascript"
formatter={command='C:\Users\studio-pc\AppData\Roaming\npm\prettier.cmd',args=["--parser","typescript"]}
auto-format=true

[[language]]
name="typescript"
auto-format=true
formatter={command='C:\Users\studio-pc\AppData\Roaming\npm\prettier.cmd',args=["--parser","typescript"]}

[[language]]
name="tsx"
formatter={command='C:\Users\studio-pc\AppData\Roaming\npm\prettier.cmd',args=["--parser","typescript"]}
auto-format=true